### ISSUE TITLE
URL is Trimmed Incorrectly

### ISSUE THREAD

**Issue by ilyaigpetrov** [saintedlama/metalsmith-canonical#2]
Look at this line: https://github.com/saintedlama/metalsmith-canonical/blob/master/index.js#L28
input url: `test.html`
output url: `tes`
Read lodash [docs] about how `_.trimEnd` works.
`url = _.trimEnd('test.html', 'index.html')` will trim chars `['i', 'n', 'd', 'e', 'x', '.', 'h', 't', 'm', 'l']` from right, including two `t`s.

[docs]: https://lodash.com/docs#trimEnd

I suggest using regular expression: `url.replace(/(?:^index)?\.html$/, '')`.

**Comment by saintedlama** [comment]
Fixed in version 1.1.4

**Comment by saintedlama** [comment]
Thanks for reporting the bug 🚀

**Comment by ilyaigpetrov** [comment]
```js
if (url.lastIndexOf(index) == url.length - index.length) {
  return url.substring(0, url.lastIndexOf(index));
}
```
1. You may do it more readable:
```js
if (url.endsWith(index)) {
  return url.substring(0, url.lastIndexOf(index)); // Also: url.replace(new RegExp(index + '$'), '');
}
```
2. Don't use `==`, use `===`. See [eqeqeq](https://eslint.org/docs/rules/eqeqeq.html).

Sorry for knocking your do with an advice, but I hope it may be useful.
