### ISSUE TITLE
Feature Request: Add an Option to Omit Extensions

### ISSUE THREAD

**Issue by ilyaigpetrov** [saintedlama/metalsmith-canonical#3]
Please, add an option to omit `.html` extension. It may have such interface:
```js
  .use(canonical({
    hostname: siteHost,
    omitIndex: true,
    omitExtensions: ['.html'],
  }))
```

**Comment by saintedlama** [comment]
The feature should remove extensions or not process files with that extension?

**Comment by ilyaigpetrov** [comment]
Remove.

**Comment by ilyaigpetrov** [comment]
Pulled a request #4 for this.
Should have asked if you are going to implement it this evening, but decided it will be an easy job to implement myself.

**Comment by ilyaigpetrov** [comment]
Do you want `['.html']` to be the default?
